[package]
org="ballerinax"
name="oracledb.driver"
version="1.0.0"
authors=["Ballerina"]
keywords=["OracleDB"]
repository="https://github.com/ballerina-platform/module-ballerinax-oracledb.driver"
license=["Apache-2.0"]
distribution = "slbeta5"

[[platform.java11.dependency]]
groupId = "com.oracle.database.jdbc"
artifactId = "ojdbc8"
version = "21.3.0.0"

[[platform.java11.dependency]]
groupId = "com.oracle.database.xml"
artifactId = "xdb"
version = "21.3.0.0"

[[platform.java11.dependency]]
groupId = "com.oracle.database.xml"
artifactId = "xmlparserv2"
version = "12.2.0.1"
