[package]
org = "ballerinax"
name = "oracledb.driver"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["OracleDB"]
repository = "https://github.com/ballerina-platform/module-ballerinax-oracledb.driver"
license = ["Apache-2.0"]
distribution = "2201.0.0"

[[platform.java11.dependency]]
path = "./lib/ojdbc8-@oracledb.driver.version@.jar"

[[platform.java11.dependency]]
path = "./lib/xdb-@oracle.xdb.version@.jar"

[[platform.java11.dependency]]
path = "./lib/xmlparserv2-@oracle.xmlparserv2.version@.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "oracledb.driver-native"
version = "@toml.version@"
path = "../native/build/libs/oracledb.driver-native-@project.version@.jar"
