[package]
org = "ballerinax"
name = "oracledb.driver"
version = "1.3.0"
authors = ["Ballerina"]
keywords = ["OracleDB"]
repository = "https://github.com/ballerina-platform/module-ballerinax-oracledb.driver"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java11]
graalvmCompatible = true

[[platform.java11.dependency]]
path = "./lib/ojdbc8-19.6.0.0.jar"

[[platform.java11.dependency]]
path = "./lib/xdb-21.3.0.0.jar"

[[platform.java11.dependency]]
path = "./lib/xmlparserv2-12.2.0.1.jar"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "oracledb.driver-native"
version = "1.3.0"
path = "../native/build/libs/oracledb.driver-native-1.3.0-SNAPSHOT.jar"
