[package]
org = "ballerinax"
name = "oracledb.driver"
version = "1.3.0"
authors = ["Ballerina"]
keywords = ["OracleDB"]
repository = "https://github.com/ballerina-platform/module-ballerinax-oracledb.driver"
license = ["Apache-2.0"]
distribution = "2201.7.0"

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
path = "./lib/ojdbc11-23.2.0.0.jar"

[[platform.java17.dependency]]
path = "./lib/xdb-23.2.0.0.jar"

[[platform.java17.dependency]]
path = "./lib/xmlparserv2-23.2.0.0.jar"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "oracledb.driver-native"
version = "1.3.0"
path = "../native/build/libs/oracledb.driver-native-1.3.0-SNAPSHOT.jar"
