[package]
org = "ballerinax"
name = "oracledb.driver"
version = "1.4.1"
authors = ["Ballerina"]
keywords = ["OracleDB"]
repository = "https://github.com/ballerina-platform/module-ballerinax-oracledb.driver"
license = ["Apache-2.0"]
distribution = "2201.11.0-20241117-133400-a3054b77"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
path = "./lib/ojdbc11-23.2.0.0.jar"

[[platform.java21.dependency]]
path = "./lib/xdb-23.2.0.0.jar"

[[platform.java21.dependency]]
path = "./lib/xmlparserv2-23.2.0.0.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "oracledb.driver-native"
version = "1.4.1"
path = "../native/build/libs/oracledb.driver-native-1.4.1-SNAPSHOT.jar"
