name: Central Publish

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select environment
        required: true
        options:
          - CENTRAL
          - DEV CENTRAL
          - STAGE CENTRAL

jobs:
  publish-release:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ballerina-platform'
    steps:
      - uses: actions/checkout@v2

      - name: Ballerina Pack
        uses: ballerina-platform/ballerina-action/@2201.0.0
        with:
          args:
            pack

      - name: Ballerina Central Push
        if: ${{ github.event.inputs.environment == 'CENTRAL' }}
        uses: ballerina-platform/ballerina-action/@2201.0.0
        env:
          BALLERINA_DEV_CENTRAL: false
          BALLERINA_STAGE_CENTRAL: false
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_ACCESS_TOKEN }}
        with:
          args:
            push

      - name: Ballerina Central Dev Push
        if: ${{ github.event.inputs.environment == 'DEV CENTRAL' }}
        uses: ballerina-platform/ballerina-action/@2201.0.0
        env:
          BALLERINA_DEV_CENTRAL: true
          BALLERINA_STAGE_CENTRAL: false
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_DEV_ACCESS_TOKEN }}
        with:
          args:
            push

      - name: Ballerina Central Stage Push
        if: ${{ github.event.inputs.environment == 'STAGE CENTRAL' }}
        uses: ballerina-platform/ballerina-action/@2201.0.0
        env:
          BALLERINA_DEV_CENTRAL: false
          BALLERINA_STAGE_CENTRAL: true
          BALLERINA_CENTRAL_ACCESS_TOKEN: ${{ secrets.BALLERINA_CENTRAL_STAGE_ACCESS_TOKEN }}
        with:
          args:
            push
